services:

  # ---------------- FRONTEND ----------------
  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - gateway
    networks:
      raft-net:

  # ---------------- GATEWAY ----------------
  gateway:
    build: ./backend/gateway
    ports:
      - "5000:5000"
    depends_on:
      - node1
      - node2
      - node3
    networks:
      raft-net:

  # ---------------- RAFT NODES ----------------
  node1:
    build: ./backend/node
    container_name: node1
    command: sh -c "cp -r /src/* /app/ && npm install && npx nodemon --legacy-watch nodex.js 1"
    volumes:
      - ./node1:/app
      - ./backend/node:/src
      - ./logs:/logs
    working_dir: /app
    networks:
      raft-net:

  node2:
    build: ./backend/node
    container_name: node2
    command: sh -c "cp -r /src/* /app/ && npm install && npx nodemon --legacy-watch nodex.js 2"
    volumes:
      - ./node2:/app
      - ./backend/node:/src
      - ./logs:/logs
    working_dir: /app
    networks:
      raft-net:

  node3:
    build: ./backend/node
    container_name: node3
    command: sh -c "cp -r /src/* /app/ && npm install && npx nodemon --legacy-watch nodex.js 3"
    volumes:
      - ./node3:/app
      - ./backend/node:/src
      - ./logs:/logs
    working_dir: /app
    networks:
      raft-net:
# ---------------- NETWORK ----------------
networks:
  raft-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
